# A minimal REAL-provider example: one AWS S3 bucket via the hashicorp/aws
# provider (resolved + verified + cached from the OpenTofu registry by the
# executor). Drive it with the tn CLI:
#
#   AWS_PROFILE=<profile> tn apply   --attr terraeNivis.aws
#   tn state show aws.aws_s3_bucket.demo
#   AWS_PROFILE=<profile> tn destroy --attr terraeNivis.aws
#
# This CREATES a real (free-tier) S3 bucket plus one small text object, and then
# destroys them.
#
# The object is the point: its CONTENT is built by Nix from the bucket's own
# apply-time output (the AWS-generated bucket name). That value cannot exist until
# the bucket is created and Nix re-evaluates with the name injected — so the two
# resources resolve across phases, and a value computed in the Nix domain becomes
# the body of a real cloud resource. That round trip — mixing the Nix and
# Terraform domains — is why this project exists.
#
# Provider settings live in Nix: `region` (and any other non-secret settings,
# e.g. default_tags) are declared here via `mkProvider` and flow into the
# provider's Configure call. Only credentials come from the environment (the AWS
# SDK default chain — AWS_PROFILE or AWS_ACCESS_KEY_ID/…), since we never bake
# secrets into Nix. `bucket` is omitted so AWS assigns a globally-unique name;
# force_destroy lets `tn destroy` delete it unconditionally.
{ terraeNivis }:
ledger:
let
  inherit (terraeNivis)
    mkResource
    mkProvider
    str
    toIR
    ;

  bucket = mkResource {
    provider = "aws";
    type = "aws_s3_bucket";
    name = "demo";
    config = {
      force_destroy = true;
      tags = { nixform-test = "terrae-nivis-aws-example"; };
    };
  };

  # A text file whose content is generated by Nix. `bucket` references the
  # bucket's output (a TF→TF edge: the object depends on the bucket), and
  # `content` is a Nix-built string that embeds the bucket's generated name (a
  # __derived value) — so the file's body is computed in Nix from a value the
  # provider produced.
  note = mkResource {
    provider = "aws";
    type = "aws_s3_object";
    name = "note";
    config = {
      bucket = bucket.refAttr "id";
      key = "hello-from-nix.txt";
      content = str [
        "This file's content was generated by Nix.\n"
        "It is stored in the bucket named: "
        (bucket.refAttr "id")
        "\n"
      ];
      content_type = "text/plain";
    };
  };
in
toIR {
  providers = {
    aws = mkProvider {
      source = "registry.opentofu.org/hashicorp/aws";
      config = {
        # Region in Nix, not the environment. Change to your region.
        region = "eu-central-1";
        # default_tags is a LIST-nested block in the AWS provider, so it takes a
        # list (of at most one) — a bare attrset is rejected at Configure time.
        default_tags = [ { tags = { managed-by = "terrae-nivis"; }; } ];
      };
    };
  };
  resources = [
    bucket
    note
  ];
  inherit ledger;
}
