#!/usr/bin/env bash
# milestone-notes.sh: generate a milestone's release-notes document
# (docs/releases/<slug>.md) from three sources:
#   - the milestone (title + definition-of-done) and its COMPLETED child epics,
#     from the beans tracker,
#   - "Highlights": blocks marked in the tutorials with
#       <!-- release-note: <title> --> ... <!-- /release-note -->
#     pulled verbatim (the verified, runnable examples),
#   - the CHANGELOG's [Unreleased] section.
#
# Deterministic (stable ordering, no per-run timestamps) so the output can be
# golden-checked by tests/check-milestone-notes.sh. Pure read + write.
#
# Usage:
#   scripts/milestone-notes.sh <milestone-id>            # write docs/releases/<slug>.md
#   scripts/milestone-notes.sh <milestone-id> --stdout   # print to stdout (for the gate's diff)
set -euo pipefail
cd "$(dirname "$0")/.."

MILESTONE="${1:-}"
MODE="${2:-file}"
if [ -z "$MILESTONE" ]; then
  echo "usage: scripts/milestone-notes.sh <milestone-id> [--stdout]" >&2
  exit 2
fi

# The tutorials scanned for release-note highlight markers (stable order).
TUTORIALS="docs/TUTORIAL-FEATURES.md docs/TUTORIAL-AWS-S3.md docs/TUTORIAL-EC2-NIXOS.md"

python3 - "$MILESTONE" "$MODE" $TUTORIALS <<'PY'
import json, os, re, subprocess, sys

milestone = sys.argv[1]
mode = sys.argv[2]
tutorials = sys.argv[3:]

# --- milestone + completed child epics from beans -------------------------
q = '{ bean(id: "%s") { id title body children { id title status type } } }' % milestone
out = subprocess.run(["beans", "query", "--json", q], capture_output=True, text=True)
if out.returncode != 0:
    sys.stderr.write("milestone-notes: beans query failed: %s\n" % out.stderr)
    sys.exit(1)
data = json.loads(out.stdout)
bean = (data.get("data") or data)["bean"]
title = bean["title"]
body = bean.get("body") or ""

# definition of done: the "## Definition of done" section of the body, if present.
dod = ""
m = re.search(r'(?ms)^##+\s*Definition of done.*?\n(.*?)(?=\n##\s|\Z)', body)
if m:
    dod = m.group(1).strip()

# completed child epics, sorted by title for a stable, readable order.
epics = sorted(
    [c for c in bean["children"] if c.get("status") == "completed"],
    key=lambda c: c["title"],
)

# --- highlights: release-note-marked blocks from the tutorials ------------
# <!-- release-note: Title --> ... <!-- /release-note -->
highlights = []  # (title, body, source)
marker = re.compile(
    r'<!--\s*release-note:\s*(?P<t>.*?)\s*-->\n(?P<b>.*?)\n<!--\s*/release-note\s*-->',
    re.S,
)
for path in tutorials:
    if not os.path.exists(path):
        continue
    text = open(path).read()
    for mm in marker.finditer(text):
        highlights.append((mm.group("t").strip(), mm.group("b").strip(), path))

# --- CHANGELOG [Unreleased] -----------------------------------------------
unreleased = ""
if os.path.exists("CHANGELOG.md"):
    # capture from just after the [Unreleased] header line to the next "## "
    # header (or EOF). Anchor on the header line so an empty Unreleased section
    # (just a blank line before the next version) yields "" rather than bleeding
    # into the next section.
    cm = re.search(r'(?ms)^##\s*\[Unreleased\][^\n]*\n(.*?)(?=^##\s|\Z)', open("CHANGELOG.md").read())
    if cm:
        unreleased = cm.group(1).strip()

# --- render ---------------------------------------------------------------
L = []
L.append("<!-- Generated by scripts/milestone-notes.sh from beans + tutorials + CHANGELOG.")
L.append("     Do not edit by hand; rerun the generator. -->")
L.append("")
L.append("# Release notes: %s" % title)
L.append("")
if dod:
    L.append("## Goal")
    L.append("")
    L.append(dod)
    L.append("")
L.append("## Highlights")
L.append("")
if highlights:
    L.append("What you can do, with verified examples from the tutorials:")
    L.append("")
    for t, b, src in highlights:
        L.append("### %s" % t)
        L.append("")
        L.append(b)
        L.append("")
        L.append("_From [%s](../../%s)._" % (os.path.basename(src), src))
        L.append("")
else:
    L.append("_(No tutorial blocks are marked with `release-note` yet.)_")
    L.append("")
L.append("## What shipped")
L.append("")
if epics:
    for e in epics:
        L.append("- %s" % e["title"])
else:
    L.append("- _(no completed epics recorded)_")
L.append("")
L.append("## Changelog (unreleased)")
L.append("")
L.append(unreleased if unreleased else "_(empty)_")
L.append("")

doc = "\n".join(L)

if mode == "--stdout":
    sys.stdout.write(doc)
else:
    # slug from the milestone title: kebab-case, before any ":".
    base = title.split(":")[0].strip().lower()
    slug = re.sub(r'[^a-z0-9]+', '-', base).strip('-')
    os.makedirs("docs/releases", exist_ok=True)
    path = os.path.join("docs/releases", slug + ".md")
    open(path, "w").write(doc)
    sys.stderr.write("wrote %s\n" % path)
PY
